name: Aktualizacja Statusu DST

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [update_bot]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie repo
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Biblioteki
        run: pip install -r requirements.txt

      - name: Start bota
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py
